CREATE database TEMP;
USE TEMP;
CREATE TABLE ACCOUNT(
ID INT PRIMARY KEY,
NAME VARCHAR(225) UNIQUE,
BALANCE INT NOT NULL DEFAULT 0
);
INSERT INTO ACCOUNT(ID,NAME)
VALUES (1,'A');


SELECT * FROM CUSTOMER;

-- ADD NEW COLUMN
ALTER TABLE ACCOUNT ADD INTEREST FLOAT NOT NULL DEFAULT 0;
SELECT * FROM ACCOUNT;

-- MODIFY 
ALTER TABLE ACCOUNT MODIFY INTEREST DOUBLE NOT NULL DEFAULT 0;
DESC account;  -- describe ACCOUNT

-- CHANGE COLUMN -- RENAME COLUMN
ALTER TABLE ACCOUNT CHANGE COLUMN INTEREST SAVING_INTEREST FLOAT NOT NULL DEFAULT 0;

-- DEOP COLUMN
ALTER TABLE ACCOUNT DROP COLUMN SAVING_INTEREST ;

-- RENAME TABLE
ALTER TABLE ACCOUNT RENAME TO ACCOUNT_DETAILS;

DROP TABLE CUSTOMER;

CREATE TABLE CUSTOMER(
ID INT PRIMARY KEY,
CNAME VARCHAR(225),
ADDRESS VARCHAR(225),
GENDER CHAR(2),
CITY VARCHAR(225),
PINCODE INT
);

INSERT INTO CUSTOMER
VALUES 
(1, 'Alice Smith', '123 Maple Street', 'F', 'New York', 10001),
(2, 'Bob Johnson', '456 Oak Avenue', 'M', 'Los Angeles', 90001),
(3, 'Carol Lee', '789 Pine Road', 'F', 'Chicago', 60601),
(4, 'David Kim', '321 Birch Blvd', 'M', 'Houston', 77001),
(5, 'Eva Brown', '654 Cedar Lane', 'F', 'Phoenix', 85001);

INSERT INTO CUSTOMER (ID, CNAME, ADDRESS, GENDER, CITY, PINCODE)
VALUES
(6, 'Frank Moore', '987 Spruce Street', 'M', 'Philadelphia', 19101),
(7, 'Grace Hall', '159 Walnut Avenue', 'F', 'San Antonio', 78201),
(8, 'Henry Adams', '753 Poplar Drive', 'M', 'San Diego', 92101),
(9, 'Isla Scott', '852 Willow Way', 'F', 'Dallas', 75201),
(10, 'Jack Turner', '951 Chestnut Blvd', 'M', 'San Jose', 95101),
(11, 'Karen Green', '111 Cypress Court', 'F', 'Austin', 73301),
(12, 'Leo Wright', '222 Redwood Road', 'M', 'Jacksonville', 32099),
(13, 'Mia Young', '333 Sequoia Street', 'F', 'Fort Worth', 76101),
(14, 'Noah King', '444 Elm Terrace', 'M', 'Columbus', 43004),
(15, 'Olivia Hill', '555 Hickory Street', 'F', 'Charlotte', 28201);

INSERT INTO CUSTOMER (ID, CNAME)
VALUES (16,'RAGA');

-- UPDATE
UPDATE CUSTOMER SET ADDRESS = 'Zoohu', GENDER='M', CITY = 'Mumbai' WHERE ID = 1;
SELECT * FROM CUSTOMER;

-- MULTIPLE ROWS UPDATE
SET SQL_SAFE_UPDATES =0;   -- FOR SAFETY PURPOSE RUN THIS COMMAND FIRST OW SQL DIDNOT GIVE U THE AUTORISE TO CHANGE ALL ROWS AT A TIME
UPDATE CUSTOMER SET PINCODE = 1000;


UPDATE CUSTOMER SET PINCODE = PINCODE+1;  -- you can write PINCODE++


-- DELETE
DELETE FROM CUSTOMER WHERE ID =1;
DELETE FROM CUSTOMER ;  -- FOR DELETE TABLE

-- DELETE CASCADE
CREATE TABLE ORDER_DETAILS(
ORDER_ID INT PRIMARY KEY,
DELEVARY_DATE DATE,
CUST_ID INT,
-- FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER(ID) ON DELETE CASCADE  -- BOTH TABLE DETAILS WILL BE DELETED
FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER(ID) ON DELETE SET NULL  -- ORDER TABLE DETAILS NOT TO BE DELETED
);

INSERT INTO ORDER_DETAILS
VALUES (1, '2019-03-13',1);


-- REPLACE
SELECT * FROM CUSTOMER;

REPLACE INTO CUSTOMER(ID,CNAME,CITY)
VALUES(4, 'RAHUL','BANKURA' );



